version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:14
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - HTTP_PORT=${HTTP_PORT}
    volumes:
      - odoo-data:/var/lib/odoo
    ports:
      - 8069:8069

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - odoo-data:/var/lib/odoo
    depends_on:
      - odoo

volumes:
  odoo-data:
  odoo-db-data:

